In [1]:
import numpy as np

In [2]:
list1 = np.arange(1,13)

In [3]:
list1


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [4]:
N = 6

# Vander package in python

In [6]:

np.vander(list1, N, increasing=True)

array([[     1,      1,      1,      1,      1,      1],
       [     1,      2,      4,      8,     16,     32],
       [     1,      3,      9,     27,     81,    243],
       [     1,      4,     16,     64,    256,   1024],
       [     1,      5,     25,    125,    625,   3125],
       [     1,      6,     36,    216,   1296,   7776],
       [     1,      7,     49,    343,   2401,  16807],
       [     1,      8,     64,    512,   4096,  32768],
       [     1,      9,     81,    729,   6561,  59049],
       [     1,     10,    100,   1000,  10000, 100000],
       [     1,     11,    121,   1331,  14641, 161051],
       [     1,     12,    144,   1728,  20736, 248832]])

# Vander matrix function written in python

In [8]:
def vander_matrix(element,N):
    out  = [] 
    for i in range(len(element)):
        list3 = []
        for j in range(0,N):
            list3.append(np.power(element[i],j))
    
        out.append(list3)
    return np.array(out)

In [10]:
matt_out2 =  vander_matrix(list1,6)

In [11]:
print(matt_out2)

[[     1      1      1      1      1      1]
 [     1      2      4      8     16     32]
 [     1      3      9     27     81    243]
 [     1      4     16     64    256   1024]
 [     1      5     25    125    625   3125]
 [     1      6     36    216   1296   7776]
 [     1      7     49    343   2401  16807]
 [     1      8     64    512   4096  32768]
 [     1      9     81    729   6561  59049]
 [     1     10    100   1000  10000 100000]
 [     1     11    121   1331  14641 161051]
 [     1     12    144   1728  20736 248832]]
